let 
  testSetEN = @[
    (key: "consign", value: "consign"),
    (key: "consigned", value: "consign"),
    (key: "consigning", value: "consign"),
    (key: "consignment", value: "consign"),
    (key: "consist", value: "consist"),
    (key: "consisted", value: "consist"),
    (key: "consistency", value: "consist"),
    (key: "consistent", value: "consist"),
    (key: "consistently", value: "consist"),
    (key: "consisting", value: "consist"),
    (key: "consists", value: "consist"),
    (key: "consolation", value: "consol"),
    (key: "consolations", value: "consol"),
    (key: "consolatory", value: "consolatori"),
    (key: "console", value: "consol"),
    (key: "consoled", value: "consol"),
    (key: "consoles", value: "consol"),
    (key: "consolidate", value: "consolid"),
    (key: "consolidated", value: "consolid"),
    (key: "consolidating", value: "consolid"),
    (key: "consoling", value: "consol"),
    (key: "consolingly", value: "consol"),
    (key: "consols", value: "consol"),
    (key: "consonant", value: "conson"),
    (key: "consort", value: "consort"),
    (key: "consorted", value: "consort"),
    (key: "consorting", value: "consort"),
    (key: "conspicuous", value: "conspicu"),
    (key: "conspicuously", value: "conspicu"),
    (key: "conspiracy", value: "conspiraci"),
    (key: "conspirator", value: "conspir"),
    (key: "conspirators", value: "conspir"),
    (key: "conspire", value: "conspir"),
    (key: "conspired", value: "conspir"),
    (key: "conspiring", value: "conspir"),
    (key: "constable", value: "constabl"),
    (key: "constables", value: "constabl"),
    (key: "constance", value: "constanc"),
    (key: "constancy", value: "constanc"),
    (key: "constant", value: "constant"),
    (key: "knack", value: "knack"),
    (key: "knackeries", value: "knackeri"),
    (key: "knacks", value: "knack"),
    (key: "knag", value: "knag"),
    (key: "knave", value: "knave"),
    (key: "knaves", value: "knave"),
    (key: "knavish", value: "knavish"),
    (key: "kneaded", value: "knead"),
    (key: "kneading", value: "knead"),
    (key: "knee", value: "knee"),
    (key: "kneel", value: "kneel"),
    (key: "kneeled", value: "kneel"),
    (key: "kneeling", value: "kneel"),
    (key: "kneels", value: "kneel"),
    (key: "knees", value: "knee"),
    (key: "knell", value: "knell"),
    (key: "knelt", value: "knelt"),
    (key: "knew", value: "knew"),
    (key: "knick", value: "knick"),
    (key: "knif", value: "knif"),
    (key: "knife", value: "knife"),
    (key: "knight", value: "knight"),
    (key: "knightly", value: "knight"),
    (key: "knights", value: "knight"),
    (key: "knit", value: "knit"),
    (key: "knits", value: "knit"),
    (key: "knitted", value: "knit"),
    (key: "knitting", value: "knit"),
    (key: "knives", value: "knive"),
    (key: "knob", value: "knob"),
    (key: "knobs", value: "knob"),
    (key: "knock", value: "knock"),
    (key: "knocked", value: "knock"),
    (key: "knocker", value: "knocker"),
    (key: "knockers", value: "knocker"),
    (key: "knocking", value: "knock"),
    (key: "knocks", value: "knock"),
    (key: "knopp", value: "knopp"),
    (key: "knot", value: "knot"),
    (key: "knots", value: "knot")
  ]

  testTextEN = "caps cries  luxurious apples lied posesses bums luxuriating hopped" &
    " delete if preceding longest finangles"


